words = ['electricity', 'donkey', 'hardware', 'xerox', 'transistor', 'computer', 'desktop',
'engineering', 'hangman', 'circuit', 'imagination', 'robot', 'memory', 'power', 
'submarine', 'chess', 'resistance', 'matrix', 'function', 'laser', 'mechanism', 
'bodyguard', 'titanic', 'global', 'ozone', 'bridge', 'technology', 'spider', 
'pyramid', 'sphere', 'member', 'warning', 'yourself', 'screen', 'language', 
'system', 'internet', 'parameter', 'traffic', 'network', 'filter', 'nucleus', 
'automatic', 'microphone', 'cassette', 'operation', 'country', 'beautiful', 
'picture', 'teacher', 'superman', 'undertaker', 'alarm', 'process', 'keyboard', 
'electron', 'certificate', 'grandfather', 'landmark', 'relativity', 'eraser',
'design', 'football', 'human', 'musician', 'egyptian', 'elephant', 'queen',
'message', 'wallpaper', 'nationality', 'answer', 'wrong', 'statement', 'forest',
'puzzle', 'voltage', 'current', 'mathematics', 'wisdom', 'dream', 'supermarket',
'database', 'collection', 'barrier', 'project', 'sunlight', 'figure', 'graph',
'battle', 'hundred', 'signal', 'thousand', 'transformation', 'daughter', 'flower',
'communication', 'microwave', 'electronic', 'peace', 'wireless', 'delete']
